# Project: c-test
# Makefile created by Steve Chang
# Date modified: 2025.11.09

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \

SRCS = $(wildcard *.$(C_FILE_EXT))

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
